title:             İSLAMİ KİTAPLAR
email:             islamikitaplareditor@gmail.com
description:       İslami baş ucu kitaplarını Epub ve azw formatında, kindle ve e-kitap okuyucularına sunuyoruz.
author:            İK Editor
#baseurl:           "/"
#url:               "http://islamikitaplar.github.io"


logo: "/img/logo.png"

# Social Profiles
github_username:   islamikitaplar

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
